# Generated by Django 2.1.5 on 2019-01-16 05:20

import json
from pathlib import Path

from django.db import migrations

APP_DIR = Path(__file__).resolve().parents[1]
JSON_DATA_PATH = '{}/mineral_data/minerals.json'.format(str(APP_DIR))


def replace_whitespace(old_dict):
    """Replaces whitespace in the keys with underscores to match the fields on the Model"""
    new_dict = {}
    for key in old_dict:
        if len(key) == 1:
            new_dict[key] = old_dict[key]
        else:
            new_key = key.replace(' ', '_')
            new_dict[new_key] = old_dict[key]
    return new_dict


def load_initial_data(apps, schema_editor):
    """Create a Mineral instance for each mineral in the json file"""
    Mineral = apps.get_model('minerals', 'Mineral')
    with open(JSON_DATA_PATH, mode='r', encoding='utf-8') as json_file:
        mineral_data = json.load(json_file)
        for mineral_dict in mineral_data:
            modified_dict = replace_whitespace(mineral_dict)
            Mineral.objects.create(**modified_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
